### ISSUE TITLE
[Component] constructor

### ISSUE THREAD

**Issue by AlexandreAndrade00** [lutzzdias/travelling-salesman-problem#4]
The API has a Component class. It should be discussed what it represents in our problem and implement it.

**Comment by AlexandreAndrade00** [comment]
In my interpretation, a Component is a city, so it should have a city ID.

**Comment by lutzzdias** [comment]
Agreed, we'll be able to get the distance between 2 cities from the problem instance and the path will be saved in the `path` variable.

**Comment by lutzzdias** [comment]
The professor criticized in class that a component would be only the next city, in his opinion, the edge (currCity -> nextCity) is better since that is what we are actually adding. The city itself will be in the solution no matter what

**Comment by AlexandreAndrade00** [comment]
I don't think that this change will change the final result. But the Component can be changed to represent an edge instead of a vertice.

**Comment by lutzzdias** [comment]
I did not fully understand the reasoning behind not using the cities as a component. In the end the outcome would be the same, perhaps it's in order to facilitate the reasoning for adding new components and allowing for non linear solution construction (eg. not necessarily start from a city, but add any arcs as long as it does not create loops)

**Comment by lutzzdias** [comment]
We can confirm the reasoning in today's PL

**Comment by lutzzdias** [comment]
closed in #27
